version: "2.4"

volumes:
  raspap_config: {}

services:
  raspap:
    build: .
    cap_add:
      - SYS_TTY_CONFIG
      - NET_ADMIN
    volumes:
      - "raspap_config:/etc/raspap"
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    privileged: true
    network_mode: host
    cgroup: host
    labels:
      io.balena.features.dbus: "1"
    devices:
      - /dev/tty0
      - /dev/tty1
    tmpfs:
      - /var/log/raspap
    restart: unless-stopped

  # https://hub.balena.io/blocks/1918776/hostname-rpi
  hostname:
    image: bh.cr/g_tomas_migone1/hostname-rpi/0.2.1
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: raspap

