version: "2.4"

volumes:
  raspap_config: {}

services:
  raspap:
    build: .
    restart: unless-stopped
    ports:
     - "80:80"
    cap_add:
      - SYS_TTY_CONFIG
      - NET_ADMIN
    volumes:
      - "raspap_config:/etc/raspap"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    network_mode: host
    pid: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
    devices:
      - /dev/tty0
      - /dev/tty1
    tmpfs:
      - /run
      - /sys/fs/cgroup
      - /var/log/raspap
    environment:
      RASPAP_SSID: raspap-webgui
      RASPAP_SSID_PASS: ChangeMe
      RASPAP_COUNTRY: GB
      RASPAP_WEBGUI_USER: admin
      RASPAP_WEBGUI_PASS: secret
      RASPAP_WEBGUI_PORT: 80

  # https://github.com/balenablocks/hostname
  # https://hub.balena.io/blocks/1918776/hostname-rpi
  hostname:
    image: bh.cr/g_tomas_migone1/hostname-rpi
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: raspap

